# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
          
      - name: Print env
        run: env
      
      - name: Build cpp
        run: g++ hw.cpp -o app
        
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: app
          retention-days: 3
          
  download-and-send:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: app
        
      - name: Display structure
        run: ls -R
        
      - name: Install curl
        run: sudo apt install curl
        
      - name: Sending
        run: curl -F "document=@app/my-artifact" -F "chat_id=${{ secrets.TELEGRAM_CHAT_ID  }}" https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument
  
